# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='room_creater',
            new_name='room_creator',
        ),
        migrations.RenameField(
            model_name='liveroom',
            old_name='room_creater',
            new_name='room_creator',
        ),
    ]
