# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170806_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertifyregister',
            name='vertifytime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 15, 42, 26, 55603)),
        ),
    ]
