#!/usr/bin/python3
#coding=utf-8


import sys, os, re
from subprocess import check_output

# 收集参数
commit_msg_filepath = sys.argv[1]

# 检测所在的分支
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
string = open(commit_msg_filepath).read()

#不能再master分之commit
if b'master' in branch:
    print('\033[1;31;40m Must be commited on a branch except master \033[0m')
    sys.exit(1)
else:
    print("commit-msg: On branch '%s'" % branch)

asc_ii_only = re.compile(r'^[\x00-\x7f]+$')
start_with_uppercase = re.compile(r'^[A-Z]')
bind_to_issue = re.compile(r'Ref #[0-9]+')
#检测中文
if not re.search(asc_ii_only,string):
    print('\033[1;31;40m Do not use Chinese \033[0m')
    sys.exit(2)
#检测首字母大写
if not re.findall(start_with_uppercase,string):
    print('\033[1;31;40m First letter must be uppercase \033[0m')
    sys.exit(3)
#检测绑定issue
if not re.findall(bind_to_issue,string):
    print('\033[1;31;40m You must bind this commit to an issue. Add \" Ref #issue_num \" to the  commit message \033[0m')
    sys.exit(4)

#测试通过
print('\033[0;32m')
print( 'Pass all tests , commit successfully!')
print('\033[0m')
sys.exit(0)